FROM saulcalla/kafka-connect-source:1.0.0

ADD ak-tools-ccloud.delta /tmp/ak-tools-ccloud.delta

ARG BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO

RUN echo $BASIC_AUTH_CREDENTIALS_SOURCE

EXPOSE 8083

ENV  CONNECT_REST_PORT 8083
ENV  CONNECT_GROUP_ID "connect"
ENV  CONNECT_CONFIG_STORAGE_TOPIC connect-configs
ENV  CONNECT_OFFSET_STORAGE_TOPIC connect-offsets
ENV  CONNECT_STATUS_STORAGE_TOPIC connect-statuses
ENV  CONNECT_REPLICATION_FACTOR 3
ENV  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR 3
ENV  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR 3
ENV  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR 3
ENV  CONNECT_KEY_CONVERTER "org.apache.kafka.connect.storage.StringConverter"
ENV  CONNECT_VALUE_CONVERTER "io.confluent.connect.avro.AvroConverter"
ENV  CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE "true"

ENV  CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE $BASIC_AUTH_CREDENTIALS_SOURCE

ENV  CONNECT_INTERNAL_KEY_CONVERTER "org.apache.kafka.connect.json.JsonConverter"
ENV  CONNECT_INTERNAL_VALUE_CONVERTER "org.apache.kafka.connect.json.JsonConverter"
ENV  CONNECT_REST_ADVERTISED_HOST_NAME "connect"

# Connect Looger
ENV  CONNECT_LOG4J_ROOT_LOGLEVEL INFO
ENV  CONNECT_LOG4J_LOGGERS org.reflections=ERROR

ENV  CLASSPATH /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.5.0.jar:/tmp/connect/lib/ojdbc6.jar

# Connect Security
ENV  CONNECT_SECURITY_PROTOCOL SASL_SSL
ENV  CONNECT_SASL_MECHANISM PLAIN
ENV  CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM "HTTPS"

# Connect Producer
ENV  CONNECT_PRODUCER_SECURITY_PROTOCOL SASL_SSL
ENV  CONNECT_PRODUCER_SASL_MECHANISM PLAIN
ENV  CONNECT_PRODUCER_INTERCEPTOR_CLASSES "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
ENV  CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL SASL_SSL
ENV  CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM PLAIN

# Connect consumer
ENV  CONNECT_CONSUMER_SECURITY_PROTOCOL SASL_SSL
ENV  CONNECT_CONSUMER_SASL_MECHANISM PLAIN
ENV  CONNECT_CONSUMER_INTERCEPTOR_CLASSES "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
ENV  CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL SASL_SSL
ENV  CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM PLAIN