apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconnectjdbc-deployment-service
  labels:
    app: kafkaconnectjdbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconnectjdbc
  template:
    metadata:
      labels:
        app: kafkaconnectjdbc
    spec:
      containers:
      - name: kafkaconnectsourcejdbc
        image: saulcalla/kafkaconnectsourcejdbc:1.0.0
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafkaconnectjdbc-config
              key: BOOTSTRAP_SERVERS
        - name: SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: SASL_JAAS_CONFIG_PROPERTY_FORMAT
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: SASL_JAAS_CONFIG
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
        - name: SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: kafkaconnectjdbc-config
              key: SCHEMA_REGISTRY_URL
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: kafkaconnectjdbc-config
              key: SCHEMA_REGISTRY_URL
        - name: CLOUD_KEY
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: CLOUD_KEY
        - name: CLOUD_SECRET
          valueFrom:
            secretKeyRef:
              name: kafkaconnectjdbc-secret
              key: CLOUD_SECRET
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaconnectjdbc-service
  labels:
    app: kafkaconnectjdbc
spec:
  type: NodePort
  selector:
    app: kafkaconnectjdbc
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083